/**
 * Mastercard Checkout Solutions Merchant Registration API
 * Registration APIs for Mastercard Checkout Solutions to submit new DPA data or check status of an existing uploaded batch
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MastercardCheckoutSolutionsMerchantRegistrationApi);
  }
}(this, function(expect, MastercardCheckoutSolutionsMerchantRegistrationApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new MastercardCheckoutSolutionsMerchantRegistrationApi.BatchStatusItems();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('BatchStatusItems', function() {
    it('should create an instance of BatchStatusItems', function() {
      // uncomment below and update the code to test BatchStatusItems
      //var instance = new MastercardCheckoutSolutionsMerchantRegistrationApi.BatchStatusItems();
      //expect(instance).to.be.a(MastercardCheckoutSolutionsMerchantRegistrationApi.BatchStatusItems);
    });

    it('should have the property action (base name: "action")', function() {
      // uncomment below and update the code to test the property action
      //var instance = new MastercardCheckoutSolutionsMerchantRegistrationApi.BatchStatusItems();
      //expect(instance).to.be();
    });

    it('should have the property serviceId (base name: "serviceId")', function() {
      // uncomment below and update the code to test the property serviceId
      //var instance = new MastercardCheckoutSolutionsMerchantRegistrationApi.BatchStatusItems();
      //expect(instance).to.be();
    });

    it('should have the property trid (base name: "trid")', function() {
      // uncomment below and update the code to test the property trid
      //var instance = new MastercardCheckoutSolutionsMerchantRegistrationApi.BatchStatusItems();
      //expect(instance).to.be();
    });

    it('should have the property programName (base name: "programName")', function() {
      // uncomment below and update the code to test the property programName
      //var instance = new MastercardCheckoutSolutionsMerchantRegistrationApi.BatchStatusItems();
      //expect(instance).to.be();
    });

    it('should have the property status (base name: "status")', function() {
      // uncomment below and update the code to test the property status
      //var instance = new MastercardCheckoutSolutionsMerchantRegistrationApi.BatchStatusItems();
      //expect(instance).to.be();
    });

    it('should have the property error (base name: "error")', function() {
      // uncomment below and update the code to test the property error
      //var instance = new MastercardCheckoutSolutionsMerchantRegistrationApi.BatchStatusItems();
      //expect(instance).to.be();
    });

    it('should have the property dpaResults (base name: "dpaResults")', function() {
      // uncomment below and update the code to test the property dpaResults
      //var instance = new MastercardCheckoutSolutionsMerchantRegistrationApi.BatchStatusItems();
      //expect(instance).to.be();
    });

  });

}));
