/**
 * Mastercard Checkout Solutions Merchant Registration API
 * Registration APIs for Mastercard Checkout Solutions to submit new DPA data or check status of an existing uploaded batch
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MastercardCheckoutSolutionsMerchantRegistrationApi);
  }
}(this, function(expect, MastercardCheckoutSolutionsMerchantRegistrationApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new MastercardCheckoutSolutionsMerchantRegistrationApi.DpaBatchStatus();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('DpaBatchStatus', function() {
    it('should create an instance of DpaBatchStatus', function() {
      // uncomment below and update the code to test DpaBatchStatus
      //var instance = new MastercardCheckoutSolutionsMerchantRegistrationApi.DpaBatchStatus();
      //expect(instance).to.be.a(MastercardCheckoutSolutionsMerchantRegistrationApi.DpaBatchStatus);
    });

    it('should have the property requestId (base name: "requestId")', function() {
      // uncomment below and update the code to test the property requestId
      //var instance = new MastercardCheckoutSolutionsMerchantRegistrationApi.DpaBatchStatus();
      //expect(instance).to.be();
    });

    it('should have the property batchId (base name: "batchId")', function() {
      // uncomment below and update the code to test the property batchId
      //var instance = new MastercardCheckoutSolutionsMerchantRegistrationApi.DpaBatchStatus();
      //expect(instance).to.be();
    });

    it('should have the property batchStatus (base name: "batchStatus")', function() {
      // uncomment below and update the code to test the property batchStatus
      //var instance = new MastercardCheckoutSolutionsMerchantRegistrationApi.DpaBatchStatus();
      //expect(instance).to.be();
    });

    it('should have the property batchStartTime (base name: "batchStartTime")', function() {
      // uncomment below and update the code to test the property batchStartTime
      //var instance = new MastercardCheckoutSolutionsMerchantRegistrationApi.DpaBatchStatus();
      //expect(instance).to.be();
    });

    it('should have the property batchEndTime (base name: "batchEndTime")', function() {
      // uncomment below and update the code to test the property batchEndTime
      //var instance = new MastercardCheckoutSolutionsMerchantRegistrationApi.DpaBatchStatus();
      //expect(instance).to.be();
    });

    it('should have the property errorMessage (base name: "errorMessage")', function() {
      // uncomment below and update the code to test the property errorMessage
      //var instance = new MastercardCheckoutSolutionsMerchantRegistrationApi.DpaBatchStatus();
      //expect(instance).to.be();
    });

    it('should have the property items (base name: "items")', function() {
      // uncomment below and update the code to test the property items
      //var instance = new MastercardCheckoutSolutionsMerchantRegistrationApi.DpaBatchStatus();
      //expect(instance).to.be();
    });

  });

}));
