/**
 * Checkout, Save Card On File, Delete Saved Card On File And Confirmations API
 *  Click to Pay checkout used by Merchants to receive payload data from the Click to Pay System and send the results of transaction authorisation back to the Click to Pay System. Endpoints are available to retrieve payload data and send the outcome of a payment or checkout. 
 *
 * The version of the OpenAPI document: 1.3.2
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CheckoutReferenceData from './CheckoutReferenceData';
import CheckoutReferenceType from './CheckoutReferenceType';

/**
 * The CheckoutReference model module.
 * @module model/CheckoutReference
 * @version 1.3.2
 */
class CheckoutReference {
    /**
     * Constructs a new <code>CheckoutReference</code>.
     * @alias module:model/CheckoutReference
     * @param type {module:model/CheckoutReferenceType} 
     * @param data {module:model/CheckoutReferenceData} 
     */
    constructor(type, data) { 
        
        CheckoutReference.initialize(this, type, data);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, type, data) { 
        obj['type'] = type;
        obj['data'] = data;
    }

    /**
     * Constructs a <code>CheckoutReference</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CheckoutReference} obj Optional instance to populate.
     * @return {module:model/CheckoutReference} The populated <code>CheckoutReference</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CheckoutReference();

            if (data.hasOwnProperty('type')) {
                obj['type'] = CheckoutReferenceType.constructFromObject(data['type']);
            }
            if (data.hasOwnProperty('data')) {
                obj['data'] = CheckoutReferenceData.constructFromObject(data['data']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CheckoutReference</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CheckoutReference</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of CheckoutReference.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // validate the optional field `data`
        if (data['data']) { // data not null
          CheckoutReferenceData.validateJSON(data['data']);
        }

        return true;
    }


}

CheckoutReference.RequiredProperties = ["type", "data"];

/**
 * @member {module:model/CheckoutReferenceType} type
 */
CheckoutReference.prototype['type'] = undefined;

/**
 * @member {module:model/CheckoutReferenceData} data
 */
CheckoutReference.prototype['data'] = undefined;






export default CheckoutReference;

