/**
 * Checkout, Save Card On File, Delete Saved Card On File And Confirmations API
 *  Click to Pay checkout used by Merchants to receive payload data from the Click to Pay System and send the results of transaction authorisation back to the Click to Pay System. Endpoints are available to retrieve payload data and send the outcome of a payment or checkout. 
 *
 * The version of the OpenAPI document: 1.3.2
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class CheckoutType.
* @enum {}
* @readonly
*/
export default class CheckoutType {
    
        /**
         * value: "CLICK_TO_PAY"
         * @const
         */
        "CLICK_TO_PAY" = "CLICK_TO_PAY";

    
        /**
         * value: "CARD_ON_FILE_TOKENIZATION"
         * @const
         */
        "CARD_ON_FILE_TOKENIZATION" = "CARD_ON_FILE_TOKENIZATION";

    
        /**
         * value: "GUEST_CHECKOUT_TOKENIZATION"
         * @const
         */
        "GUEST_CHECKOUT_TOKENIZATION" = "GUEST_CHECKOUT_TOKENIZATION";

    
        /**
         * value: "INSTALLMENTS"
         * @const
         */
        "INSTALLMENTS" = "INSTALLMENTS";

    

    /**
    * Returns a <code>CheckoutType</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/CheckoutType} The enum <code>CheckoutType</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

