/**
 * Checkout, Save Card On File, Delete Saved Card On File And Confirmations API
 *  Click to Pay checkout used by Merchants to receive payload data from the Click to Pay System and send the results of transaction authorisation back to the Click to Pay System. Endpoints are available to retrieve payload data and send the outcome of a payment or checkout. 
 *
 * The version of the OpenAPI document: 1.3.2
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PhoneNumber from './PhoneNumber';

/**
 * The CheckoutMaskedConsumer model module.
 * @module model/CheckoutMaskedConsumer
 * @version 1.3.2
 */
class CheckoutMaskedConsumer {
    /**
     * Constructs a new <code>CheckoutMaskedConsumer</code>.
     * @alias module:model/CheckoutMaskedConsumer
     */
    constructor() { 
        
        CheckoutMaskedConsumer.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CheckoutMaskedConsumer</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CheckoutMaskedConsumer} obj Optional instance to populate.
     * @return {module:model/CheckoutMaskedConsumer} The populated <code>CheckoutMaskedConsumer</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CheckoutMaskedConsumer();

            if (data.hasOwnProperty('maskedFirstName')) {
                obj['maskedFirstName'] = ApiClient.convertToType(data['maskedFirstName'], 'String');
            }
            if (data.hasOwnProperty('maskedLastName')) {
                obj['maskedLastName'] = ApiClient.convertToType(data['maskedLastName'], 'String');
            }
            if (data.hasOwnProperty('maskedFullName')) {
                obj['maskedFullName'] = ApiClient.convertToType(data['maskedFullName'], 'String');
            }
            if (data.hasOwnProperty('maskedEmailAddress')) {
                obj['maskedEmailAddress'] = ApiClient.convertToType(data['maskedEmailAddress'], 'String');
            }
            if (data.hasOwnProperty('maskedMobileNumber')) {
                obj['maskedMobileNumber'] = PhoneNumber.constructFromObject(data['maskedMobileNumber']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CheckoutMaskedConsumer</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CheckoutMaskedConsumer</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['maskedFirstName'] && !(typeof data['maskedFirstName'] === 'string' || data['maskedFirstName'] instanceof String)) {
            throw new Error("Expected the field `maskedFirstName` to be a primitive type in the JSON string but got " + data['maskedFirstName']);
        }
        // ensure the json data is a string
        if (data['maskedLastName'] && !(typeof data['maskedLastName'] === 'string' || data['maskedLastName'] instanceof String)) {
            throw new Error("Expected the field `maskedLastName` to be a primitive type in the JSON string but got " + data['maskedLastName']);
        }
        // ensure the json data is a string
        if (data['maskedFullName'] && !(typeof data['maskedFullName'] === 'string' || data['maskedFullName'] instanceof String)) {
            throw new Error("Expected the field `maskedFullName` to be a primitive type in the JSON string but got " + data['maskedFullName']);
        }
        // ensure the json data is a string
        if (data['maskedEmailAddress'] && !(typeof data['maskedEmailAddress'] === 'string' || data['maskedEmailAddress'] instanceof String)) {
            throw new Error("Expected the field `maskedEmailAddress` to be a primitive type in the JSON string but got " + data['maskedEmailAddress']);
        }
        // validate the optional field `maskedMobileNumber`
        if (data['maskedMobileNumber']) { // data not null
          PhoneNumber.validateJSON(data['maskedMobileNumber']);
        }

        return true;
    }


}



/**
 * Masked first name of the Consumer.
 * @member {String} maskedFirstName
 */
CheckoutMaskedConsumer.prototype['maskedFirstName'] = undefined;

/**
 * Masked last name of the Consumer.
 * @member {String} maskedLastName
 */
CheckoutMaskedConsumer.prototype['maskedLastName'] = undefined;

/**
 * Masked full name of the Consumer.
 * @member {String} maskedFullName
 */
CheckoutMaskedConsumer.prototype['maskedFullName'] = undefined;

/**
 * Masked Consumer email address.
 * @member {String} maskedEmailAddress
 */
CheckoutMaskedConsumer.prototype['maskedEmailAddress'] = undefined;

/**
 * @member {module:model/PhoneNumber} maskedMobileNumber
 */
CheckoutMaskedConsumer.prototype['maskedMobileNumber'] = undefined;






export default CheckoutMaskedConsumer;

