/**
 * Checkout, Save Card On File, Delete Saved Card On File And Confirmations API
 *  Click to Pay checkout used by Merchants to receive payload data from the Click to Pay System and send the results of transaction authorisation back to the Click to Pay System. Endpoints are available to retrieve payload data and send the outcome of a payment or checkout. 
 *
 * The version of the OpenAPI document: 1.3.2
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Detail from './Detail';

/**
 * The Details model module.
 * @module model/Details
 * @version 1.3.2
 */
class Details {
    /**
     * Constructs a new <code>Details</code>.
     * @alias module:model/Details
     */
    constructor() { 
        
        Details.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Details</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Details} obj Optional instance to populate.
     * @return {module:model/Details} The populated <code>Details</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Details();

            if (data.hasOwnProperty('detail')) {
                obj['detail'] = ApiClient.convertToType(data['detail'], [Detail]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Details</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Details</code>.
     */
    static validateJSON(data) {
        if (data['detail']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['detail'])) {
                throw new Error("Expected the field `detail` to be an array in the JSON data but got " + data['detail']);
            }
            // validate the optional field `detail` (array)
            for (const item of data['detail']) {
                Detail.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * Object containing the error detail.
 * @member {Array.<module:model/Detail>} detail
 */
Details.prototype['detail'] = undefined;






export default Details;

